<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <Authors>esnya</Authors>
    <Description>A Resonite mod created with TurboAudioStream</Description>
    <RepositoryUrl>https://github.com/esnya/ResoniteTurboAudioStream</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>$(RepositoryUrl)</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright (c) 2025 $(Authors)</Copyright>
    <PackageTags>Resonite,Mod,ResoniteModLoader,Latency,Audio</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Version>0.1.2</Version>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DebugType Condition="'$(Configuration)'=='Debug'">embedded</DebugType>
    <DebugType Condition="'$(Configuration)'=='Release'">pdbonly</DebugType>
    <Optimize Condition="'$(Configuration)'=='Release'">true</Optimize>
    <AssemblyTitle>$(MSBuildProjectName)</AssemblyTitle>
    <Product>$(MSBuildProjectName)</Product>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-all</AnalysisLevel>
    <WarningLevel>9999</WarningLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <WarningsNotAsErrors>NU1701</WarningsNotAsErrors>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(ResonitePath)'==''">
    <ResonitePath>$(MSBuildThisFileDirectory)Resonite/</ResonitePath>
    <ResonitePath Condition="Exists('C:\Program Files (x86)\Steam\steamapps\common\Resonite\')"
      >C:\Program Files (x86)\Steam\steamapps\common\Resonite\</ResonitePath
    >
    <ResonitePath Condition="Exists('$(HOME)/.steam/steam/steamapps/common/Resonite/')"
      >$(HOME)/.steam/steam/steamapps/common/Resonite/</ResonitePath
    >
  </PropertyGroup>

  <PropertyGroup>
    <ResonitePath>$([MSBuild]::EnsureTrailingSlash('$(ResonitePath)'))</ResonitePath>
    <ResoniteManagedPath>$(ResonitePath)Resonite_Data\Managed\</ResoniteManagedPath>
    <ResoniteModsPath>$(ResonitePath)rml_mods</ResoniteModsPath>
    <ResoniteHotReloadPath>$(ResonitePath)rml_mods/HotReloadMods</ResoniteHotReloadPath>
    <ResoniteLibsPath>$(ResonitePath)rml_libs/</ResoniteLibsPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ResoniteModLoader">
      <HintPath>$(ResonitePath)Libraries/ResoniteModLoader.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="HarmonyLib">
      <HintPath>$(ResoniteLibsPath)0Harmony.dll</HintPath>
      <HintPath Condition="Exists('$(ResonitePath)0Harmony.dll')"
        >$(ResonitePath)0Harmony.dll</HintPath
      >
      <Private>false</Private>
    </Reference>
    <Reference Include="FrooxEngine">
      <HintPath Condition="Exists('$(ResoniteManagedPath)FrooxEngine.dll')"
        >$(ResoniteManagedPath)FrooxEngine.dll</HintPath
      >
      <HintPath
        Condition="!Exists('$(ResoniteManagedPath)FrooxEngine.dll') and Exists('$(ResonitePath)FrooxEngine.dll')"
        >$(ResonitePath)FrooxEngine.dll</HintPath
      >
      <Private>false</Private>
    </Reference>
    <Reference Include="Elements.Core">
      <HintPath Condition="Exists('$(ResoniteManagedPath)Elements.Core.dll')"
        >$(ResoniteManagedPath)Elements.Core.dll</HintPath
      >
      <HintPath
        Condition="!Exists('$(ResoniteManagedPath)Elements.Core.dll') and Exists('$(ResonitePath)Elements.Core.dll')"
        >$(ResonitePath)Elements.Core.dll</HintPath
      >
      <Private>false</Private>
    </Reference>
    <Reference Include="Elements.Assets">
      <HintPath Condition="Exists('$(ResoniteManagedPath)Elements.Assets.dll')"
        >$(ResoniteManagedPath)Elements.Assets.dll</HintPath
      >
      <HintPath
        Condition="!Exists('$(ResoniteManagedPath)Elements.Assets.dll') and Exists('$(ResonitePath)Elements.Assets.dll')"
        >$(ResonitePath)Elements.Assets.dll</HintPath
      >
      <Private>false</Private>
    </Reference>
    <Reference Include="POpusCodec">
      <HintPath Condition="Exists('$(ResoniteManagedPath)POpusCodec.dll')"
        >$(ResoniteManagedPath)POpusCodec.dll</HintPath
      >
      <HintPath
        Condition="!Exists('$(ResoniteManagedPath)POpusCodec.dll') and Exists('$(ResonitePath)POpusCodec.dll')"
        >$(ResonitePath)POpusCodec.dll</HintPath
      >
      <Private>false</Private>
    </Reference>
    <Reference Include="Awwdio">
      <HintPath Condition="Exists('$(ResoniteManagedPath)Awwdio.dll')"
        >$(ResoniteManagedPath)Awwdio.dll</HintPath
      >
      <HintPath
        Condition="!Exists('$(ResoniteManagedPath)Awwdio.dll') and Exists('$(ResonitePath)Awwdio.dll')"
        >$(ResonitePath)Awwdio.dll</HintPath
      >
      <Private>false</Private>
    </Reference>
    <Reference Include="ResoniteHotReloadLib" Condition="'$(Configuration)'=='Debug'">
      <HintPath>$(ResoniteLibsPath)ResoniteHotReloadLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory).github\**\*" LinkBase=".github" />
    <EditorConfigFiles Remove="$(MSBuildProjectDirectory)**/*.editorconfig" />
  </ItemGroup>
</Project>
