name: Static Checks

on:
  push:
    branches:
      - master
      - main
      - ci
      - ci/*
  pull_request:
    branches:
      - master
      - main
      - ci
      - ci/*

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Run dotnet format whitespace (verify)
        run: dotnet format whitespace --verify-no-changes
